version: '3'
services:
  postgres-db:
    image: postgres:13-alpine3.17
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bigbytes
  server:
    image: bigbytes/data
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    command: "python bigbytes/server/server.py --host ${HOST} --port ${PORT} --project ${PROJECT} --manage-instance ${MANAGE_INSTANCE}"
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - ECS_CLUSTER_NAME=$ECS_CLUSTER_NAME
      - ECS_CONTAINER_NAME=$ECS_CONTAINER_NAME
      - ECS_TASK_DEFINITION=$ECS_TASK_DEFINITION
      - ENV=dev
      - GCP_PROJECT_ID=$GCP_PROJECT_ID
      - GCP_REGION=$GCP_REGION
      - MAGE_DATABASE_CONNECTION_URL=postgresql+psycopg2://postgres:postgres@postgres-db:5432/bigbytes
      - MAX_NUMBER_OF_FILE_VERSIONS=$MAX_NUMBER_OF_FILE_VERSIONS
      - REQUIRE_USER_AUTHENTICATION=$REQUIRE_USER_AUTHENTICATION
      - path_to_keyfile=$GCP_PATH_TO_CREDENTIALS
      - AUTHENTICATION_MODE=$AUTHENTICATION_MODE
      - LDAP_SERVER=$LDAP_SERVER
      - LDAP_BIND_DN=$LDAP_BIND_DN
      - LDAP_BIND_PASSWORD=$LDAP_BIND_PASSWORD
      - LDAP_BASE_DN=$LDAP_BASE_DN
      - LDAP_AUTHENTICATION_FILTER=$LDAP_AUTHENTICATION_FILTER
      - LDAP_AUTHORIZATION_FILTER=$LDAP_AUTHORIZATION_FILTER
      - LDAP_ADMIN_USERNAME=$LDAP_ADMIN_USERNAME
      - SERVER_VERBOSITY=$SERVER_VERBOSITY
      - DISABLE_NOTEBOOK_EDIT_ACCESS=$DISABLE_NOTEBOOK_EDIT_ACCESS
    ports:
      - 6789:6789
    volumes:
      - .:/home/src
      - ~/.aws:/root/.aws
      - ~/.mage_data:/root/.mage_data
    restart: on-failure:5
    stdin_open: true # used for interactive debugging
    tty: true # used for interactive debugging
  app:
    image: bigbytes/data
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    depends_on:
      - server
    command: ./scripts/install_and_run.sh
    ports:
      - 3000:3000
    volumes:
      - ./bigbytes/frontend/.babelrc:/home/src/bigbytes/frontend/.babelrc
      - ./bigbytes/frontend/.eslintrc.js:/home/src/bigbytes/frontend/.eslintrc.js
      - ./bigbytes/frontend/api:/home/src/bigbytes/frontend/api
      - ./bigbytes/frontend/components:/home/src/bigbytes/frontend/components
      - ./bigbytes/frontend/context:/home/src/bigbytes/frontend/context
      - ./bigbytes/frontend/hocs:/home/src/bigbytes/frontend/hocs
      - ./bigbytes/frontend/interfaces:/home/src/bigbytes/frontend/interfaces
      - ./bigbytes/frontend/next-env.d.ts:/home/src/bigbytes/frontend/next-env.d.ts
      - ./bigbytes/frontend/next.config.js:/home/src/bigbytes/frontend/next.config.js
      - ./bigbytes/frontend/oracle:/home/src/bigbytes/frontend/oracle
      - ./bigbytes/frontend/package.json:/home/src/bigbytes/frontend/package.json
      - ./bigbytes/frontend/pages:/home/src/bigbytes/frontend/pages
      - ./bigbytes/frontend/public:/home/src/bigbytes/frontend/public
      - ./bigbytes/frontend/scripts:/home/src/bigbytes/frontend/scripts
      - ./bigbytes/frontend/storage:/home/src/bigbytes/frontend/storage
      - ./bigbytes/frontend/stories:/home/src/bigbytes/frontend/stories
      - ./bigbytes/frontend/styles:/home/src/bigbytes/frontend/styles
      - ./bigbytes/frontend/tsconfig.json:/home/src/bigbytes/frontend/tsconfig.json
      - ./bigbytes/frontend/utils:/home/src/bigbytes/frontend/utils
      - ./bigbytes/frontend/yarn.lock:/home/src/bigbytes/frontend/yarn.lock
    working_dir: /home/src/bigbytes/frontend
