apiVersion: v1
kind: ServiceAccount
metadata:
  name: bigbytes-user

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: job-manager
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch", "extensions"]
  resources: ["jobs", "jobs/status"]
  verbs: ["create", "delete", "get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bigbytes-job-manager
  namespace: default
subjects:
- kind: ServiceAccount
  name: bigbytes-user # Name of the ServiceAccount
  namespace: default
roleRef:
  kind: Role # This must be Role or ClusterRole
  name: job-manager # This must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Pod
metadata:
  name: bigbytes-server
spec:
  containers:
  - name: bigbytes-server
    image: bigbytes/bigbytes:latest
    ports:
    - containerPort: 6789
    volumeMounts:
    - name: bigbytes-fs
      mountPath: /home/src
    env:
      - name: KUBE_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
  volumes:
  - name: bigbytes-fs
    hostPath:
      path: /path/to/bigbytes_project
  serviceAccountName: bigbytes-user
